### ISSUE TITLE
Foregit MVP

### ISSUE THREAD

**Issue by maria** [maria/foregit#1]
## Need

``` gherkin
As a developer
I want to build an MVP
So that I can learn by doing
And asset the project guidelines
```
## Deliverables
- A tool which will synchronize a Foreman infrastructure with a Git repository, for a given resource
- ~~A controller to synchronize Git updates with Foreman~~ Next phase
- A controller to synchronize Foreman with the Git repo
### Prerequisites
- [Foreman API](http://theforeman.org/api_v2.html)
- [How to build a gem](http://guides.rubygems.org/make-your-own-gem/)
### TODOs
- [x] Select a resource from Foreman to be synchronized. Choices: architectures, operating systems, hosts-- We will synchronize **architectures, hosts groups, OSs**
- [x] Define project structure
- [x] Create Foreman API binding
- [x] Create sync command

**Comment by maria** [comment]
Done. We will migrate the gem to a hammer-cli plugin.
