### ISSUE TITLE
Foregit Structure

### ISSUE THREAD

**Issue by maria** [maria/foregit#2]
## Need

``` gherkin
As a developer 
I want to define the library structure
So that I can easily organize the codebase
```
## Deliverables
- Directories with READMEs for each resource
- A scaffold for the codebase
## TODOs
- [x]  investigate how a Ruby gem is structured
- [x] identify project resources
- [x] create directories and READMEs

**Comment by iNecas** [comment]
Usually, all the Ruby libraries nowadays have something like forgit.gemspec file for installation, Gemfile for devel setup, `lib/forgit.rb` and `lib/forgit` directory for the code, test for tests, They all really look the same, e.g. https://github.com/theforeman/hammer-cli

**Comment by maria** [comment]
What about bin? Also, I was thinking that I should write an App wrapper for Foreman, that should go in lib also, right?

**Comment by iNecas** [comment]
Yeah, bin is good for executables.

What do you mean be App wrapper?

**Comment by maria** [comment]
I wrote the Api wrapper part without searching if something already exists.  I found foreman-api, I will reuse it. :-)

**Comment by iNecas** [comment]
Ah, the foreman_api gem is deprecated, instead this one should be used https://github.com/Apipie/apipie-bindings, it's not specific to Foreman, but as Foreman uses apipie for documenting the API, it serves nicely for this purpose.

Here is a simple example on how it's being used https://github.com/theforeman/puppet-foreman/blob/master/lib/puppet/provider/foreman_smartproxy/rest_v2.rb#L11

**Comment by maria** [comment]
Thanks!
